config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/auth/google_oauth2/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  post "/locations/:location_id/items/new" => "items#create"
  post "/locations/:location_id/items/:id/edit" => "items#update"
  resources :locations do
    resources :items do
      collection {post :import}
      resources :statuses, only: [:create]
      get "checkin" => "statuses#checkin", :as => "checkin"
      get "checkout" => "statuses#checkout", :as => "checkout"
      get "req" => "statuses#req", :as => "req"
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :location
  has_many :statuses, dependent: :destroy
  default_scope -> {order(name: :asc)}
  mount_uploader :image, PictureUploader
  validates :name, presence: true, length: {maximum: 50}
  validates :description, length: {maximum:255}
  validate :image_size

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      @item = Item.create! row.to_hash
      Status.create!(item_id: @item.id, name: "In", holder: nil, due: nil)
    end
  end

  def self.search(search)
    if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
  end

  private
  # Validates the size of an uploaded picture
  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in

  def index
    @location = Location.find(params[:location_id])
    @items = Item.order(name: :asc)
  end

  def show
    @location = Location.find(params[:location_id])
    @item = Item.find(params[:id])
    @last_in = Status.where("item_id == ?", params[:id]).where("name == ?", "In").last
    @future_statuses = Status.where("item_id == ?", params[:id]).where("name != ?", "In").where("created_at >= ?", @last_in.created_at)
    @past_statuses = Status.where("item_id == ?", params[:id]).where("name != ?", "In").where("due_date <= ?", @last_in)
    if @status = Status.where("item_id == ?", @item.id).where("start_time <= ?", Date.today).where("due >= ?", Date.today).where("created_at >= ?", @last_in.created_at).last
    else @status = Status.where("item_id == ?", @item.id).where("start_time <= ?", Date.today).where("created_at >= ?", @last_in.created_at).last
    end
  end

  def new
    @location = Location.find(params[:location_id])
    @item = Item.new
    @status = Status.new
  end

  def create
    @location = Location.find(params[:location_id])
    @item = Item.new(item_params)
    if @item.save
      @status = Status.new(item_id: @item.id, name: "In", holder: nil, due: nil).save
      flash[:success] = "#{@item.name} added to the tracker!"
      redirect_to location_path(@item.location_id)
    else
      render "items/new"
    end
  end

  def edit
    @location = Location.find(params[:location_id])
    @item = Item.find(params[:id])
    @status = Status.where(item_id: @item.id).last
  end

  def update
    @location = Location.find(params[:location_id])
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = "#{@item.name} updated!"
      redirect_to location_item_path(@location.id, @item.id)
    else
      render "items/edit"
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item deleted"
    redirect_to location_path(params[:location_id])
  end

  def import
    @location = Location.find(params[:location_id])
    Item.import(params[:file])
      flash[:success] = "Items imported!"
      redirect_to location_path(@location.id)
  # else
  #    flash[:danger] = "Something went wrong. Check your file and try again."
  #    redirect_to location_path(@location.id)
  #  end
  end

  private

    def item_params
      params.require(:item).permit(:name, :description, :image, :location_id)
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_calendar.html.erb
<h2>Availability</h2>
<% @future_statuses.each do |status| %>
  <% if status.due != nil %>
    <% @date_range = status.start_time..status.due %>
    <% @holder = status.holder %>
  <% end %>
<%end %>
<%= month_calendar do |date| %>
  <%= date.strftime("%d") %>
  <% if !@date_range.nil? %>
    <% if @date_range.cover?(date) %>
      <% if current_user.admin? %>
        <div>
          <%= @holder %>
        </div>
      <% else %>
        <div>
          Booked
        </div>
      <% end %>
    <% else %>
      <div>
        <%= link_to "Request", location_item_req_path(@location.id, @item.id, start_time: date) %>
      </div>
    <% end %>
  <% else %>
    <div>
      <%= link_to "Request", location_item_req_path(@location.id, @item.id, start_time: date) %>
    </div>
  <% end %>
<% end %>

app/views/items/_descriptionbody.html.erb
<div>
  <span><%= image_tag(@item.image, alt: @item.name)%></span>
  <br>
  <br>
  <span><b>Status: </b><%= "#{@status.name}" %></span>
  <br>
  <% if current_user.admin? %>
    <% if @status.name != "In" %>
        <span><b>Holder: </b><%= "#{@status.holder}" %></span>
        <br>
        <span><b>Due Date: </b><%= "#{@status.due.to_s(format= :long)}" %></span>
        <br>
    <% end %>
  <% end %>
    <span><b>Description: </b><%= @item.description %></span>
</div>

app/views/items/_editdeletelinks.html.erb
( <%= link_to "Edit Item", edit_location_item_path(@location.id, @item.id) %> | <%= link_to "Delete Item", location_item_path(@location.id, @item.id), method: :delete, data: {confirm: "Are you sure you want to delete #{@item.name}?"} %> )

app/views/items/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :description %>
<%= f.text_field :description, class: 'form-control' %>

<%= f.label :image %>
<%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>

<script type="text/javascript">
$('#item_image').bind('change', function(){
  var size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 5){
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
});
</script>

app/views/items/_historytable.html.erb
<% if current_user.admin? %>
<h2>History</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Holder</th>
      <th>Checkout Date</th>
      <th>Due Date</th>
      <th>Days Out</th>
    </tr>
  </thead>
  <tbody>
  <% Status.where(item_id: @item.id, name: "Out").each do |status| %>
    <tr>
      <td><%= status.holder %></td>
      <td><%= status.created_at.to_date.to_s(:long) %></td>
      <td><%= status.due.to_s(:long) %></td>
      <td><%= (status.due.to_date - status.created_at.to_date).to_i %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/items/edit.html.erb
<%= provide(:title, "Edit Item") %>
<div class="container">
  <h1><%= "Edit: #{@item.name}"%></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for([@location, @item]) do |f| %>
        <%= render 'shared/item_error_messages' %>
        <%= render 'items/fields', f: f %>
        <br>
        <%= f.submit "Save Edits", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<%= provide(:title, "New Item")%>
<div class="container">
  <h1>Add Item to Inventory</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for([@location, @item], html: { multipart: true }) do |f| %>
        <%= render "shared/item_error_messages" %>
        <%= render "items/fields", f: f %>
        <%= f.hidden_field :location_id, :value => @location.id %>
        <br>
        <%= f.submit "Add Item to Tracker", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<%= provide(:title, "#{@item.name}") %>
<div class="container">
  <div>
    <h1><%= @item.name %></h1>
    <% if current_user.admin? %>
      <%= render "items/editdeletelinks" %>
    <% end %>
  </div>
  <div class="panel-body">
    <%= render "items/descriptionbody" %>
  </div>
  <div>
    <%= render "items/calendar" %>
    <%= render "items/historytable" %>
    <%= link_to "Back to Inventory", location_path(@location.id) %>
  </div>
</div>