config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/auth/google_oauth2/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  post "/locations/:location_id/items/new" => "items#create"
  post "/locations/:location_id/items/:id/edit" => "items#update"
  resources :locations do
    resources :items do
      collection {post :import}
      resources :statuses, only: [:create]
      get "checkin" => "statuses#checkin", :as => "checkin"
      get "checkout" => "statuses#checkout", :as => "checkout"
      get "req" => "statuses#req", :as => "req"
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :items, dependent: :destroy
  default_scope -> {order(name: :asc)}
  validates :name, presence: true, length: {maximum: 50}

  def self.search(search)
    if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :logged_in

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = "#{@location.name} added to the tracker!"
      redirect_to @location
    else
      render "locations/new"
    end
  end

  def index
    @locations = Location.search(params[:location_search]).order(name: :asc).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @location = Location.find(params[:id])
    @items = Item.where(location_id: @location.id).search(params[:item_search])
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      flash[:success] = "#{@location.name} updated!"
      redirect_to @location
    else
      render "locations/edit"
    end
  end

  def destroy
    @location = Location.find(params[:id]).destroy
    flash[:success] = "#{@location.name} and all associated items deleted"
    redirect_to locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<%= provide(:title, "Edit Location") %>
<div class="container">
  <h1><%= "Edit: #{@location.name}"%></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@location) do |f| %>
        <%= render 'shared/location_error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.submit "Save Edits", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<%= provide(:title, "Locations") %>
<div class="container">
  <h1>Locations</h1>

  <%= form_tag locations_path, :method => "get" do %>
    <p>
      <%= text_field_tag :location_search, params[:location_search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Items</th>
        <% if current_user.super_admin? %>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.name, location%></td>
        <td><%= Item.where(location_id: location.id).count %></td>
        <% if current_user.super_admin? %>
          <td><%= link_to "Edit", edit_location_path(location.id) %> | <%= link_to "Delete", location_path(location.id), method: :delete, data: {confirm: "Are you sure you want to delete #{location.name}? Note: this will also delete all of the items associated with the city."} %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @locations %>
  <% if current_user.super_admin? %>
    <p><%= link_to "+ Add New Location", new_location_path %></p>
  <% end %>
</div>

app/views/locations/index.mobile.erb
This is the mobile site?

app/views/locations/new.html.erb
<%= provide(:title, "New Location")%>
<div class="container">
  <h1>Add Location</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@location) do |f| %>
        <%= render "shared/location_error_messages" %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.submit "Add Location to Tracker", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<div class="container">
  <h1><%= @location.name %></h1>
  <%= form_tag location_path(location_id: @location.id), :method => "get" do %>
    <p>
      <%= text_field_tag :item_search, params[:item_search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <% if current_user.admin? %>
          <th>Holder</th>
          <th>Due</th>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <% @last_in = Status.where("item_id == ?", item.id).where("name == ?", "In").last %>
        <% if @status = Status.where("item_id == ?", item.id).where("start_time <= ?", Date.today).where("due >= ?", Date.today).where("created_at >= ?", @last_in.created_at).last %>
        <% else @status = Status.where("item_id == ?", item.id).where("start_time <= ?", Date.today).where("created_at >= ?", @last_in.created_at).last %>
        <% end %>
        <tr>
          <td><%= link_to item.name, location_item_path(@location.id, item.id)%></td>
          <td><%= @status.name %></td>
          <% if current_user.admin? %>
            <td><%= @status.holder %></td>
            <% unless @status.due.nil? %>
              <td><%= (@status.due).to_s(:long) %></td>
              <td><%= link_to "Check In", location_item_checkin_path(@location.id, item.id) %></td>
            <% else %>
              <td></td>
              <td><%= link_to "Check Out", location_item_checkout_path(@location.id, item.id) %></td>
            <% end %>
          <% else %>
            <td><%= link_to "Request", location_item_req_path(@location.id, item.id) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if current_user.admin? %>
    <p><%= link_to "+ Add New Item", new_location_item_path(@location.id) %></p>
  <% end %>
  <% if current_user.super_admin? %>
    <h1>Import CSV</h1>
    <%= form_tag import_location_items_path(params[:id]), multipart: true do %>
      <%= file_field_tag :file %>
      <br>
      <%= submit_tag "Import" %>
    <% end %>
  <% end %>
</div>