config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/auth/google_oauth2/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  post "/locations/:location_id/items/new" => "items#create"
  post "/locations/:location_id/items/:id/edit" => "items#update"
  resources :locations do
    resources :items do
      collection {post :import}
      resources :statuses, only: [:create]
      get "checkin" => "statuses#checkin", :as => "checkin"
      get "checkout" => "statuses#checkout", :as => "checkout"
      get "req" => "statuses#req", :as => "req"
    end
  end

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
    <%= link_to"I/O", locations_path %>
    </div>
    <div id="navbar" class="navbar-right">
    <% if current_user %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Locations <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View All", locations_path %></li>
            <li role="separator" class="divider"></li>
            <% Location.all.each do |location| %>
            <li><%= link_to location.name, location %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Info", root_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Log in with Google", "/auth/google_oauth2/" %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | I/O</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'mobile' if mobile_device? %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "layouts/navigation" %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%=key%>"><%= value %></div>
    <% end %>
    <%= yield %>
    <div class=container>
      <% if mobile_device? %>
        <%= link_to "Full Site", :mobile => 0 %>
      <% else %>
        <%= link_to "Mobile Site", :mobile => 1 %>
      <% end %>
    </div>
</body>
</html>